name: cmake-test

on:
  push:
    branches: [ "main" ]
    paths:
      - '*.c'
      - '*.h'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ "main" ]
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Ninja build tool
      run: sudo apt install ninja-build
      
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Configure CMake
      run: cmake -GNinja -DTARGET_GROUP=test .

    - name: Build
      # Build your program with the given configuration
      run: ninja -v

    - name: Test
      run: ctest --verbose
      
