name: cmake-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Ninja buil tool
      run: apt install ninja-build
      
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -GNinja -DTARGET_GROUP=test .

    - name: Build
      # Build your program with the given configuration
      run: ninja -v

    - name: Test
      run: ctest --verbose
      
